- name: install pip3
  apt:
    name: python3-pip
    update_cache: yes

- name: copy requirements
  copy: 
    src: "{{src_requirements_path}}requirements.txt"
    dest: "{{destination_path}}"

- name: install requirements.txt
  command: "pip3 install -r requirements.txt"

- name: clean requirements.txt
  file:
    path: "{{destination_path}}requirements.txt"
    state: absent 
